CAEN qtp Demo: main.c File Reference
main.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <stdarg.h>
#include <unistd.h>
#include <sys/time.h>
#include <memory.h>
#include <ctype.h>
#include "common_defs.h"
#include "../include/CAENVMETool/cvt_board_commons.h"
#include "../include/CAENVMETool/cvt_common_defs.h"
#include "../include/CAENVMETool/cvt_V792.h"
#include "user_settings.h"
Defines
#define Sleep(t) usleep((t)*1000)
#define GNUPLOT_COMMAND "gnuplot"
#define HDR_STR " HDR - GEO : %08x CRATE : %08x CH COUNT : %08x \n"
#define DATUM_STR " DATUM - GEO : %08x CHANNEL : %08x ADC : %08x UN : %08x OV : %08x \n"
#define NOT_VALID_DATUM_STR " NOT VALID DATUM - \n"
#define EOB_STR " EOB - GEO : %08x EVENT COUNTER : %08x \n"
#define UNKNOWN_STR "\n??? UNKNOWN TAG ??? - READ WORD : %08x \n\n"
#define MAX_HISTO_SAMPLES (CVT_V792_DATUM_ADC_MSK+ 1)
#define MAX_HISTO_CHANNELS MAX_THRESHOLD_NUM
Functions
static int channel_select (int act_channel)
Select the new channel index to be plotted.
long get_time ()
Returns the time in milliseconds since first procedure call.
int main (int argc, char **argv)
CAENVMETool demo usage for the V792 board.
Variables
const char * HISTO_FILENAME = "histo.dat"
Define Documentation
#define DATUM_STR " DATUM - GEO : %08x CHANNEL : %08x ADC : %08x UN : %08x OV : %08x \n"
Definition at line 52 of file main.c.
Referenced by main().
#define EOB_STR " EOB - GEO : %08x EVENT COUNTER : %08x \n"
Definition at line 54 of file main.c.
Referenced by main().
#define GNUPLOT_COMMAND "gnuplot"
Definition at line 45 of file main.c.
Referenced by main().
#define HDR_STR " HDR - GEO : %08x CRATE : %08x CH COUNT : %08x \n"
Definition at line 51 of file main.c.
Referenced by main().
#define MAX_HISTO_CHANNELS MAX_THRESHOLD_NUM
Definition at line 58 of file main.c.
Referenced by channel_select(), and main().
#define MAX_HISTO_SAMPLES (CVT_V792_DATUM_ADC_MSK+ 1)
Definition at line 57 of file main.c.
Referenced by main().
#define NOT_VALID_DATUM_STR " NOT VALID DATUM - \n"
Definition at line 53 of file main.c.
Referenced by main().
#define Sleep (t) usleep((t)*1000)
Definition at line 28 of file main.c.
Referenced by main().
#define UNKNOWN_STR "\n??? UNKNOWN TAG ??? - READ WORD : %08x \n\n"
Definition at line 55 of file main.c.
Function Documentation
int channel_select (int act_channel) [static]
Select the new channel index to be plotted.
Parameters:
act_channel The actual selected channel index
Returns:
The new selected channel index
Definition at line 80 of file main.c.
References getstring(), and MAX_HISTO_CHANNELS.
Referenced by main().
long get_time (void)
Returns the time in milliseconds since first procedure call.
Returns:
The time in milliseconds since first procedure call
Definition at line 107 of file main.c.
Referenced by main().
int main (int argc, char ** argv)
CAENVMETool demo usage for the V792 board.
Setups a V792 board, reads some events and stores into output file
Parameters:
argc number of command line arguments
*argv[] command line arguments' list
Returns:
= 0 procedure completed correctly: < 0 some error occurred
Definition at line 147 of file main.c.
References CAENVME_Init(), channel_select(), cvSuccess, CVT_QTP_DATA_TYPE_MSK, CVT_QTP_DATUM, CVT_QTP_EOB, CVT_QTP_GET_EOB_EVENT_COUNT, CVT_QTP_GET_EOB_GEO, CVT_QTP_GET_HDR_CH_COUNT, CVT_QTP_GET_HDR_CRATE, CVT_QTP_GET_HDR_GEO, CVT_QTP_HEADER, CVT_QTP_NOT_VALID_DATUM, CVT_V1785, CVT_V1785_GET_DATUM_CH, CVT_V775_TYPE_A, CVT_V775_TYPE_N, CVT_V775A_GET_DATUM_CH, CVT_V775N_GET_DATUM_CH, CVT_V785_TYPE_A, CVT_V785_TYPE_N, CVT_V785A_GET_DATUM_CH, CVT_V785N_GET_DATUM_CH, cvt_V792_close(), cvt_V792_data_clear(), CVT_V792_GET_DATUM_ADC, CVT_V792_GET_DATUM_GEO, CVT_V792_GET_DATUM_OV, CVT_V792_GET_DATUM_UN, cvt_V792_get_piggy_back_str(), cvt_V792_get_system_info(), cvt_V792_open(), cvt_V792_read_MEB(), cvt_V792_set_acquisition_mode(), cvt_V792_set_dual_range_zero_suppression(), cvt_V792_set_readout_mode(), cvt_V792_set_sliding_scale(), cvt_V792_set_zero_suppression(), CVT_V792_TYPE_A, CVT_V792_TYPE_N, CVT_V792A_GET_DATUM_CH, CVT_V792N_GET_DATUM_CH, CVT_V965, CVT_V965_GET_DATUM_CH, CVT_V965_TYPE_A, CVT_V965A_GET_DATUM_CH, cvV1718, cvV2718, DATUM_STR, EOB_STR, FALSE, get_time(), getch, GNUPLOT_COMMAND, HDR_STR, HISTO_FILENAME, kbhit, user_setting_data::m_acquisition_mode_param, user_setting_data::m_base_address, user_setting_data::m_board_number, user_setting_data::m_board_type, acquisition_mode_param::m_common_stop_enable, acquisition_mode_param::m_count_all_events, acquisition_mode_param::m_empty_enable, user_setting_data::m_gnu_plot_path, user_setting_data::m_gnu_plot_refresh, zero_suppression_param::m_high_thresholds_buff, user_setting_data::m_link_number, user_setting_data::m_num_events, acquisition_mode_param::m_overflow_suppression_enable, user_setting_data::m_parsed_output_filename, user_setting_data::m_qtp_type, user_setting_data::m_raw_output_filename, acquisition_mode_param::m_sliding_scale_enable, zero_suppression_param::m_step_threshold, zero_suppression_param::m_thresholds_buff, cvt_V792_data::m_type, acquisition_mode_param::m_valid_suppression_enable, acquisition_mode_param::m_zero_suppression_enable, user_setting_data::m_zero_suppression_param, MAX_FILENAME_LENGHT, MAX_HISTO_CHANNELS, MAX_HISTO_SAMPLES, NOT_VALID_DATUM_STR, Sleep, TRACE, TRACE1, TRUE, user_settings_close(), user_settings_open(), and user_settings_parse_input_param().
Variable Documentation
const char* HISTO_FILENAME = "histo.dat"
Definition at line 62 of file main.c.
Referenced by main().