CAEN qtp Demo: user_settings.h File Reference
user_settings.h File Reference
#include "common_defs.h"
#include "../include/CAENVMETool/cvt_board_commons.h"
#include "../include/CAENVMETool/cvt_common_defs.h"
#include "../include/CAENVMETool/cvt_V792.h"
Data Structures
struct acquisition_mode_param
Acquisition mode parameters.
struct zero_suppression_param
struct user_setting_data
User settings data structure.
Defines
#define MAX_FILENAME_LENGHT 255
#define MAX_THRESHOLD_NUM 32
Maximun Number of threshold registers.
Functions
BOOL user_settings_open (user_setting_data *p_data)
init user setting module
BOOL user_settings_close (user_setting_data *p_data)
closes user setting module (frees allocated resources)
BOOL user_settings_parse_input_param (user_setting_data *p_data, int argc, char *argv[])
Scan<s user input parameters.
Define Documentation
#define MAX_FILENAME_LENGHT 255
Maximum filenam length
Definition at line 25 of file user_settings.h.
Referenced by main(), parse_config_file(), and user_settings_open().
#define MAX_THRESHOLD_NUM 32
Maximun Number of threshold registers.
Definition at line 26 of file user_settings.h.
Referenced by parse_zero_suppression_thresholds().
Function Documentation
BOOL user_settings_close (user_setting_data * p_data)
closes user setting module (frees allocated resources)
Parameters:
*p_data data buffer pointer
Returns:
TRUE procedure completed correctly
Note:
call after any other methods
Definition at line 124 of file user_settings.c.
References user_setting_data::m_parsed_output_filename, user_setting_data::m_raw_output_filename, and TRUE.
Referenced by main().
BOOL user_settings_open (user_setting_data * p_data)
init user setting module
Parameters:
*p_data data buffer pointer
Returns:
TRUE procedure completed correctly
Note:
call before any other methods
Definition at line 69 of file user_settings.c.
References DEF_BASE_ADDRESS, DEF_CONFIG_FILENAME, DEF_GNU_PLOT_PATH, DEF_GNU_PLOT_REFRESH, DEF_GNU_PLOT_X_SCALE, DEF_NUM_EVENTS, DEF_PARSED_OUTPUT_FILENAME, DEF_RAW_OUTPUT_FILENAME, DEF_V792_TYPE, DEF_ZERO_SUPPRESSION_PARAMS, FALSE, user_setting_data::m_acquisition_mode_param, user_setting_data::m_base_address, acquisition_mode_param::m_common_stop_enable, user_setting_data::m_config_filename, acquisition_mode_param::m_count_all_events, acquisition_mode_param::m_empty_enable, user_setting_data::m_gnu_plot_path, user_setting_data::m_gnu_plot_refresh, user_setting_data::m_gnu_plot_x_scale, zero_suppression_param::m_high_thresholds_buff, user_setting_data::m_num_events, acquisition_mode_param::m_overflow_suppression_enable, user_setting_data::m_parsed_output_filename, user_setting_data::m_qtp_type, user_setting_data::m_raw_output_filename, acquisition_mode_param::m_sliding_scale_enable, zero_suppression_param::m_thresholds_buff, acquisition_mode_param::m_valid_suppression_enable, acquisition_mode_param::m_zero_suppression_enable, user_setting_data::m_zero_suppression_param, MAX_FILENAME_LENGHT, parse_zero_suppression_thresholds(), TRACE, and TRUE.
Referenced by main().
BOOL user_settings_parse_input_param (user_setting_data * p_data, int argc, char * argv[])
Scan<s user input parameters.
Parameters:
*p_data data buffer pointer
argc number of input parameters
*argv[] string parameters list
Returns:
TRUE procedure completed correctly
Definition at line 140 of file user_settings.c.
References DEF_CONFIG_FILENAME, FALSE, kbhit, user_setting_data::m_config_filename, parse_config_file(), TRACE, TRACE1, and TRUE.
Referenced by main().