CAEN qtp Demo: user_settings.c File Reference
user_settings.c File Reference
#include <malloc.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <stdarg.h>
#include <unistd.h>
#include <sys/time.h>
#include <memory.h>
#include "common_defs.h"
#include "user_settings.h"
Defines
#define Sleep(t) usleep((t)*1000)
#define DEF_RAW_OUTPUT_FILENAME "raw_values.dat"
#define DEF_PARSED_OUTPUT_FILENAME "parsed_values.dat"
#define DEF_NUM_EVENTS -1
#define DEF_BASE_ADDRESS 0x3210
#define DEF_BOARD_TYPE_STR "V792A"
#define DEF_V792_TYPE CVT_V792_TYPE_A
#define DEF_ZERO_SUPPRESSION_PARAMS "0"
#define DEF_CONFIG_FILENAME "CAENqtpDemo.conf"
#define DEF_GNU_PLOT_PATH ""
#define DEF_GNU_PLOT_REFRESH 500
#define DEF_GNU_PLOT_X_SCALE 0.3f
Functions
static BOOL parse_zero_suppression_thresholds (const char *line, UINT16 *thresholds_buff)
static BOOL parse_config_file (user_setting_data *p_data)
static char * trim (char charset[], int n_chars, const char *string)
BOOL user_settings_open (user_setting_data *p_data)
init user setting module
BOOL user_settings_close (user_setting_data *p_data)
closes user setting module (frees allocated resources)
BOOL user_settings_parse_input_param (user_setting_data *p_data, int argc, char *argv[])
Scan<s user input parameters.
BOOL parse_acquisition_mode_param (const char *line, acquisition_mode_param *target)
Define Documentation
#define DEF_BASE_ADDRESS 0x3210
Default boards' base address
Definition at line 42 of file user_settings.c.
Referenced by user_settings_open().
#define DEF_BOARD_TYPE_STR "V792A"
Default V792's type string
Definition at line 43 of file user_settings.c.
#define DEF_CONFIG_FILENAME "CAENqtpDemo.conf"
Configuration file default filename
Definition at line 46 of file user_settings.c.
Referenced by user_settings_open(), and user_settings_parse_input_param().
#define DEF_GNU_PLOT_PATH ""
GnuPlot folder default path
Definition at line 47 of file user_settings.c.
Referenced by user_settings_open().
#define DEF_GNU_PLOT_REFRESH 500
Gnu plot refresh rate (msec)
Definition at line 48 of file user_settings.c.
Referenced by user_settings_open().
#define DEF_GNU_PLOT_X_SCALE 0.3f
GnuPlot X conversion factor
Definition at line 49 of file user_settings.c.
Referenced by user_settings_open().
#define DEF_NUM_EVENTS -1
Default number of events
Definition at line 41 of file user_settings.c.
Referenced by user_settings_open().
#define DEF_PARSED_OUTPUT_FILENAME "parsed_values.dat"
Parsed board values default filename
Definition at line 39 of file user_settings.c.
Referenced by user_settings_open().
#define DEF_RAW_OUTPUT_FILENAME "raw_values.dat"
Raw board values default filename
Definition at line 38 of file user_settings.c.
Referenced by user_settings_open().
#define DEF_V792_TYPE CVT_V792_TYPE_A
Default V792's type
Definition at line 44 of file user_settings.c.
Referenced by user_settings_open().
#define DEF_ZERO_SUPPRESSION_PARAMS "0"
Default zero suppression thresholds
Definition at line 45 of file user_settings.c.
Referenced by user_settings_open().
#define Sleep (t) usleep((t)*1000)
Definition at line 29 of file user_settings.c.
Function Documentation
BOOL parse_acquisition_mode_param (const char * line, acquisition_mode_param * target)
Definition at line 454 of file user_settings.c.
References FALSE, acquisition_mode_param::m_empty_enable, acquisition_mode_param::m_overflow_suppression_enable, acquisition_mode_param::m_sliding_scale_enable, acquisition_mode_param::m_zero_suppression_enable, and TRUE.
BOOL parse_config_file (user_setting_data * p_data) [static]
Definition at line 182 of file user_settings.c.
References CVT_V1785, CVT_V775_TYPE_A, CVT_V775_TYPE_N, CVT_V785_TYPE_A, CVT_V785_TYPE_N, CVT_V792_TYPE_A, CVT_V792_TYPE_N, CVT_V862_TYPE_A, CVT_V965, CVT_V965_TYPE_A, FALSE, user_setting_data::m_acquisition_mode_param, user_setting_data::m_base_address, user_setting_data::m_board_number, acquisition_mode_param::m_common_stop_enable, user_setting_data::m_config_filename, acquisition_mode_param::m_count_all_events, user_setting_data::m_debug, acquisition_mode_param::m_empty_enable, user_setting_data::m_gnu_plot_path, user_setting_data::m_gnu_plot_refresh, user_setting_data::m_gnu_plot_x_scale, zero_suppression_param::m_high_thresholds_buff, user_setting_data::m_link_number, user_setting_data::m_num_events, acquisition_mode_param::m_overflow_suppression_enable, user_setting_data::m_parsed_output_filename, user_setting_data::m_qtp_type, user_setting_data::m_raw_output_filename, acquisition_mode_param::m_sliding_scale_enable, zero_suppression_param::m_step_threshold, zero_suppression_param::m_thresholds_buff, acquisition_mode_param::m_valid_suppression_enable, acquisition_mode_param::m_zero_suppression_enable, user_setting_data::m_zero_suppression_param, MAX_FILENAME_LENGHT, parse_zero_suppression_thresholds(), stricmp, TRACE, TRACE1, trim(), and TRUE.
Referenced by user_settings_parse_input_param().
BOOL parse_zero_suppression_thresholds (const char * line, UINT16 * thresholds_buff) [static]
Definition at line 431 of file user_settings.c.
References MAX_THRESHOLD_NUM, strnicmp, trim(), and TRUE.
Referenced by parse_config_file(), and user_settings_open().
char * trim (char charset[], int n_chars, const char * string) [static]
Definition at line 401 of file user_settings.c.
References FALSE, and TRUE.
Referenced by parse_config_file(), and parse_zero_suppression_thresholds().
BOOL user_settings_close (user_setting_data * p_data)
closes user setting module (frees allocated resources)
Parameters:
*p_data data buffer pointer
Returns:
TRUE procedure completed correctly
Note:
call after any other methods
Definition at line 124 of file user_settings.c.
References user_setting_data::m_parsed_output_filename, user_setting_data::m_raw_output_filename, and TRUE.
Referenced by main().
BOOL user_settings_open (user_setting_data * p_data)
init user setting module
Parameters:
*p_data data buffer pointer
Returns:
TRUE procedure completed correctly
Note:
call before any other methods
Definition at line 69 of file user_settings.c.
References DEF_BASE_ADDRESS, DEF_CONFIG_FILENAME, DEF_GNU_PLOT_PATH, DEF_GNU_PLOT_REFRESH, DEF_GNU_PLOT_X_SCALE, DEF_NUM_EVENTS, DEF_PARSED_OUTPUT_FILENAME, DEF_RAW_OUTPUT_FILENAME, DEF_V792_TYPE, DEF_ZERO_SUPPRESSION_PARAMS, FALSE, user_setting_data::m_acquisition_mode_param, user_setting_data::m_base_address, acquisition_mode_param::m_common_stop_enable, user_setting_data::m_config_filename, acquisition_mode_param::m_count_all_events, acquisition_mode_param::m_empty_enable, user_setting_data::m_gnu_plot_path, user_setting_data::m_gnu_plot_refresh, user_setting_data::m_gnu_plot_x_scale, zero_suppression_param::m_high_thresholds_buff, user_setting_data::m_num_events, acquisition_mode_param::m_overflow_suppression_enable, user_setting_data::m_parsed_output_filename, user_setting_data::m_qtp_type, user_setting_data::m_raw_output_filename, acquisition_mode_param::m_sliding_scale_enable, zero_suppression_param::m_thresholds_buff, acquisition_mode_param::m_valid_suppression_enable, acquisition_mode_param::m_zero_suppression_enable, user_setting_data::m_zero_suppression_param, MAX_FILENAME_LENGHT, parse_zero_suppression_thresholds(), TRACE, and TRUE.
Referenced by main().
BOOL user_settings_parse_input_param (user_setting_data * p_data, int argc, char * argv[])
Scan<s user input parameters.
Parameters:
*p_data data buffer pointer
argc number of input parameters
*argv[] string parameters list
Returns:
TRUE procedure completed correctly
Definition at line 140 of file user_settings.c.
References DEF_CONFIG_FILENAME, FALSE, kbhit, user_setting_data::m_config_filename, parse_config_file(), TRACE, TRACE1, and TRUE.
Referenced by main().