#!/bin/sh

#
#    This software is Copyright by the Board of Trustees of Michigan
#    State University (c) Copyright 2005.
#
#    You may use this software under the terms of the GNU public license
#    (GPL).  The terms of this license are described at:
#
#     http://www.gnu.org/licenses/gpl.txt
#
#     Author:
#             Ron Fox
#            NSCL
#            Michigan State University
#            East Lansing, MI 48824-1321
#

#   start wish \
exec tclsh  ${0} ${@}

#
#  Assume the tclserver is in the same directory as us:
#

set here [file dirname [info script]]
set tclserver [file join $here tclserver]
set script    [file join $here ReadoutShell.tcl]

eval exec $tclserver $script  $argv -pManaged -aReadout_GUI >&@ stdout

exit 0