# scalerParameterDialog_ui.tcl --
#
# UI generated by GUI Builder Build 107673 on 2005-08-11 16:37:06 from:
#    //homedir/home2/fox/My Documents/DAQDocs/2005a/daq/DirectoryStructure/code/scalerParameterDialog.ui
# THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
# The associated callback file should be modified instead.
#

# Declare the namespace for this dialog
namespace eval scalerParameterDialog {}

package require Tk
# scalerParameterDialog::ui --
#
#   Create the UI for this dialog.
#
# ARGS:
#   root     the parent window for this form
#   args     a catch-all for other args, but none are expected
#
proc scalerParameterDialog::ui {root args} {
    # this handles '.' as a special case
    set base [expr {($root == ".") ? "" : $root}]
    variable ROOT $root
    variable BASE $base
    variable channels
    variable period


    # Widget Initialization
    labelframe $base._labelframe_1 \
	    -relief flat \
	    -text {Number of scalers:}
    labelframe $base._labelframe_2 \
	    -relief flat \
	    -text {Scaler Readout Period (seconds):}
    frame $base._frame_1 \
	    -borderwidth 2 \
	    -relief groove
    label $base._label_1 \
	    -text {Scaler Parameters}
    spinbox $base.channels \
            -from      0  \
	    -to 10000 \
	    -increment 1 -textvariable scalerParameterDialog::channels
    spinbox $base.period \
	    -from 1 \
	    -to 3600 \
	    -increment 1 -textvariable scalerParameterDialog::period
    button $base.ok \
	    -command [namespace code [list ok_command]] \
	    -text {  Ok    }
    button $base.cancel \
	    -command [namespace code [list cancel_command]] \
	    -text Cancel


    # Geometry Management

    grid $base._labelframe_1 -in $root -row 2 -column 1 \
	    -columnspan 6 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky news
    grid $base._labelframe_2 -in $root -row 3 -column 1 \
	    -columnspan 6 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky news
    grid $base._frame_1 -in $root -row 4 -column 1 \
	    -columnspan 6 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky news
    grid $base._label_1 -in $root -row 1 -column 1 \
	    -columnspan 6 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky {}
    grid $base.channels -in $base._labelframe_1 -row 1 -column 1 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky {}
    grid $base.period -in $base._labelframe_2 -row 1 -column 1 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky {}
    grid $base.ok -in $base._frame_1 -row 1 -column 1 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky {}
    grid $base.cancel -in $base._frame_1 -row 1 -column 3 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky {}

    # Resize Behavior
    grid rowconfigure $root 1 -weight 0 -minsize 40 -pad 0
    grid rowconfigure $root 2 -weight 0 -minsize 40 -pad 0
    grid rowconfigure $root 3 -weight 0 -minsize 40 -pad 0
    grid rowconfigure $root 4 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $root 1 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $root 2 -weight 0 -minsize 30 -pad 0
    grid columnconfigure $root 3 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $root 4 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $root 5 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $root 6 -weight 0 -minsize 40 -pad 0
    grid rowconfigure $base._frame_1 1 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $base._frame_1 1 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $base._frame_1 2 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $base._frame_1 3 -weight 0 -minsize 40 -pad 0
    grid rowconfigure $base._labelframe_1 1 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $base._labelframe_1 1 -weight 0 -minsize 59 -pad 0
    grid rowconfigure $base._labelframe_2 1 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $base._labelframe_2 1 -weight 0 -minsize 40 -pad 0
}
