# selectReadout_ui.tcl --
#
# UI generated by GUI Builder Build 107673 on 2005-08-12 11:37:15 from:
#    //homedir/home2/fox/My Documents/DAQDocs/2005a/daq/DirectoryStructure/code/selectReadout.ui
# THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
# The associated callback file should be modified instead.
#

# Declare the namespace for this dialog
namespace eval selectReadout {}

package require Tk
# selectReadout::ui --
#
#   Create the UI for this dialog.
#
# ARGS:
#   root     the parent window for this form
#   args     a catch-all for other args, but none are expected
#
proc selectReadout::ui {root args} {
    # this handles '.' as a special case
    set base [expr {($root == ".") ? "" : $root}]
    variable ROOT $root
    variable BASE $base


    # Widget Initialization
    labelframe $base._labelframe_1 \
	    -relief flat \
	    -text Host
    labelframe $base._labelframe_2 \
	    -relief flat \
	    -text {Path to readout program}
    frame $base._frame_1 \
	    -relief groove \
	    -width 3
    label $base._label_1 \
	    -text {Select Readout Host and Program}
    entry $base.hostname \
	    -invalidcommand [namespace code [list hostname_invalidcommand]] \
	    -validatecommand [namespace code [list hostname_validatecommand]] \
	    -xscrollcommand [namespace code [list hostname_xscrollcommand]]
    button $base.browse \
	    -command [namespace code [list browse_command]] \
	    -text Browse...
    entry $base.path \
	    -invalidcommand [namespace code [list path_invalidcommand]] \
	    -validatecommand [namespace code [list path_validatecommand]] \
	    -width 30 \
	    -xscrollcommand [namespace code [list path_xscrollcommand]]
    button $base.ok \
	    -command [namespace code [list ok_command]] \
	    -text {  Ok  }
    button $base.cancel \
	    -command [namespace code [list cancel_command]] \
	    -text Cancel


    # Geometry Management

    grid $base._labelframe_1 -in $root -row 2 -column 1 \
	    -columnspan 8 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky news
    grid $base._labelframe_2 -in $root -row 3 -column 1 \
	    -columnspan 8 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky news
    grid $base._frame_1 -in $root -row 4 -column 1 \
	    -columnspan 8 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky news
    grid $base._label_1 -in $root -row 1 -column 1 \
	    -columnspan 7 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky {}
    grid $base.hostname -in $base._labelframe_1 -row 1 -column 1 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky w
    grid $base.browse -in $base._labelframe_2 -row 1 -column 2 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky {}
    grid $base.path -in $base._labelframe_2 -row 1 -column 1 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky ew
    grid $base.ok -in $base._frame_1 -row 1 -column 1 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky {}
    grid $base.cancel -in $base._frame_1 -row 1 -column 3 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky {}

    # Resize Behavior
    grid rowconfigure $root 1 -weight 0 -minsize 40 -pad 0
    grid rowconfigure $root 2 -weight 0 -minsize 40 -pad 0
    grid rowconfigure $root 3 -weight 0 -minsize 40 -pad 0
    grid rowconfigure $root 4 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $root 1 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $root 2 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $root 3 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $root 4 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $root 5 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $root 6 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $root 7 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $root 8 -weight 0 -minsize 40 -pad 0
    grid rowconfigure $base._frame_1 1 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $base._frame_1 1 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $base._frame_1 2 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $base._frame_1 3 -weight 0 -minsize 40 -pad 0
    grid rowconfigure $base._labelframe_1 1 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $base._labelframe_1 1 -weight 0 -minsize 2 -pad 0
    grid columnconfigure $base._labelframe_1 2 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $base._labelframe_1 3 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $base._labelframe_1 4 -weight 0 -minsize 40 -pad 0
    grid rowconfigure $base._labelframe_2 1 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $base._labelframe_2 1 -weight 0 -minsize 138 -pad 0
    grid columnconfigure $base._labelframe_2 2 -weight 0 -minsize 11 -pad 0
}
