# interface generated by SpecTcl version 1.1 from H:/Wincluster/DAQDocs/See/DVDburn/seeburnoutput.ui
#   root     is the parent window for this user interface

proc seeburnoutput_ui {root args} {

	# this treats "." as a special case

	if {$root == "."} {
	    set base ""
	} else {
	    set base $root
	}
    
	text $base.output \
		-height 1 \
		-width 1 \
		-yscrollcommand "$base.scrollbar#1 set"

	scrollbar $base.scrollbar#1 \
		-command "$base.output yview" \
		-orient v

	button $base.cancel \
		-command KillBurn \
		-text Cancel


	# Geometry management

	grid $base.output -in $root	-row 1 -column 1  \
		-columnspan 2 \
		-sticky nesw
	grid $base.scrollbar#1 -in $root	-row 1 -column 3  \
		-sticky ns
	grid $base.cancel -in $root	-row 2 -column 2 

	# Resize behavior management

	grid rowconfigure $root 1 -weight 1 -minsize 436
	grid rowconfigure $root 2 -weight 0 -minsize 30
	grid columnconfigure $root 1 -weight 0 -minsize 30
	grid columnconfigure $root 2 -weight 0 -minsize 442
	grid columnconfigure $root 3 -weight 0 -minsize 30
# additional interface code
# end additional interface code

}


# Allow interface to be run "stand-alone" for testing

catch {
    if [info exists embed_args] {
	# we are running in the plugin
	seeburnoutput_ui .
    } else {
	# we are running in stand-alone mode
	if {$argv0 == [info script]} {
	    wm title . "Testing seeburnoutput_ui"
	    seeburnoutput_ui .
	}
    }
}
