# interface generated by SpecTcl version 1.1 from H:/Wincluster/DAQDocs/See/DVDburn/TopGUi.ui
#   root     is the parent window for this user interface

proc TopGUi_ui {root args} {

	# this treats "." as a special case

	if {$root == "."} {
	    set base ""
	} else {
	    set base $root
	}
    
	frame $base.frame#2

	frame $base.frame#1

	label $base.label#3 \
		-text {SEETF DVD Burn procedure}

	radiobutton $base.radiobutton#1 \
		-justify left \
		-text {All Runs} \
		-textvariable example_2 \
		-value 1 \
		-variable all

	radiobutton $base.radiobutton#2 \
		-justify left \
		-text {Select Runs} \
		-value 0 \
		-variable all

	label $base.label#1 \
		-text {First Run Number:}

	entry $base.entry#1 \
		-textvariable FirstRun

	label $base.label#2 \
		-text {Last Run Number}

	entry $base.entry#2 \
		-cursor {} \
		-textvariable LastRun

	button $base.button#1 \
		-command Burn \
		-text Burn

	button $base.button#2 \
		-command exit \
		-text Cancel


	# Geometry management

	grid $base.frame#2 -in $root	-row 5 -column 1  \
		-columnspan 3
	grid $base.frame#1 -in $root	-row 1 -column 2  \
		-columnspan 2
	grid $base.label#3 -in $base.frame#1	-row 1 -column 1 
	grid $base.radiobutton#1 -in $root	-row 2 -column 1  \
		-sticky nw
	grid $base.radiobutton#2 -in $root	-row 3 -column 1  \
		-sticky nw
	grid $base.label#1 -in $root	-row 3 -column 2 
	grid $base.entry#1 -in $root	-row 3 -column 3 
	grid $base.label#2 -in $root	-row 4 -column 2 
	grid $base.entry#2 -in $root	-row 4 -column 3 
	grid $base.button#1 -in $base.frame#2	-row 1 -column 1 
	grid $base.button#2 -in $base.frame#2	-row 1 -column 2 

	# Resize behavior management

	grid rowconfigure $base.frame#2 1 -weight 0 -minsize 30
	grid columnconfigure $base.frame#2 1 -weight 0 -minsize 30
	grid columnconfigure $base.frame#2 2 -weight 0 -minsize 30

	grid rowconfigure $root 1 -weight 0 -minsize 30
	grid rowconfigure $root 2 -weight 0 -minsize 30
	grid rowconfigure $root 3 -weight 0 -minsize 30
	grid rowconfigure $root 4 -weight 0 -minsize 30
	grid rowconfigure $root 5 -weight 0 -minsize 30
	grid columnconfigure $root 1 -weight 0 -minsize 30
	grid columnconfigure $root 2 -weight 0 -minsize 30
	grid columnconfigure $root 3 -weight 0 -minsize 30

	grid rowconfigure $base.frame#1 1 -weight 0 -minsize 30
	grid columnconfigure $base.frame#1 1 -weight 0 -minsize 41
# additional interface code
global all
set all 1;                             # Default is record all runs.

# end additional interface code

}


# Allow interface to be run "stand-alone" for testing

catch {
    if [info exists embed_args] {
	# we are running in the plugin
	TopGUi_ui .
    } else {
	# we are running in stand-alone mode
	if {$argv0 == [info script]} {
	    wm title . "Testing TopGUi_ui"
	    TopGUi_ui .
	}
    }
}
