#!/usr/bin/python

import ROOT as root
import MySQLdb
import array, time, smtplib, libcaenhv, os, sys
from ctypes import *

#email settings
sender = 'xedaq@astro18.astronevis.columbia.edu'
receiver = ['mda2149@columbia.edu', 'mcfatelin@gmail.com', 'zg@phys.columbia.edu']
#receiver = ['mda2149@columbia.edu', 'marc.weber@astro.columbia.edu']
message1 = """From: xedaq <xedaq@astro18.astronevis.columbia.edu>
To: Matt <mda2149@columbia.edu>, Qing <mcfatelin@gmail.com>, Zach <zg@phys.columbia.edu>
Subject: PMT Tripped - automatic restart occuring

PMT Tripped - commencing automatic restart
"""

message2 = """From: xedaq <xedaq@astro18.astronevis.columbia.edu>
To: Matt <mda2149@columbia.edu>, Luke <luke.goetzke@gmail.com>, Marc <marc.weber@astro.columbia.edu>
Subject: PMT Tripped Multiple Times in 5 minutes

Potential Problem with PMT tripping - program will terminate (to avoid excessive restarts) and must be restarted.  If you wish, you can manually reset PMT using caenhv.py.
"""



prevTime = 0

timeOfPrevReset = [0, 0, 0, 0, 0, 0]

deviceName = 'caen0'
measurementName = ''

sqlConnect = MySQLdb.connect('astro18.astronevis.columbia.edu', 'smac_reader', 'wq12op09', 'smac')
sqlCursor = sqlConnect.cursor()

while 1:
	sqlCursor.execute('select * from ' + deviceName + ' where ' + deviceName + '_id > ' + str(time.time() - 30) + ';')
	deviceData = sqlCursor.fetchall()

	#print len(deviceData)
	#print deviceData

	length = len(deviceData)

	#check length of device data to see if something new is available
	if length > 0 and deviceData[0][0] != prevTime:
		prevTime = deviceData[length - 1][0]
		for i in xrange(0, 6):
			if deviceData[length - 1][3 + 3*i] > 7:
				#check for  same PMT tripping multiple times
				if time.time() - timeOfPrevReset[i] < 300:
					#send email that you are shutting program down
					#because of potential problem with PMT
					smtpObj = smtplib.SMTP('localhost')
					smtpObj.sendmail(sender, receiver, message2)
					
					time.sleep(90)
					sys.exit()
			
				#send email that you are resetting PMT
				smtpObj = smtplib.SMTP('localhost')
				smtpObj.sendmail(sender, receiver, message1)
				
				#reset PMT voltage
				handle = c_int()
				res = libcaenhv.init_system(system=2, link_type=0, arg='129.236.254.45', username='user', password='q1w2e3r4', handle=byref(handle))

				parameter_values_list = [int(1)]
				res = libcaenhv.set_channel_parameter_bypass(handle=handle, slot=0, parameter_name='Pw', nb_channels=1, channels_list=[i + 1], parameter_values_list=parameter_values_list)

				libcaenhv.deinit_system(handle)

				#note time of this reset
				timeOfPrevReset[i] = time.time()



	time.sleep(17)

