/control/execute macros/no_verbose.mac
/tracking/verbose 0

/vis/scene/create
/vis/open VRML2FILE

/vis/viewer/set/viewpointThetaPhi 0 180 deg
/vis/viewer/zoom 10.0

/tracking/storeTrajectory 1
/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate

/xe/gun/particle neutron
/xe/gun/energytype Mono
/xe/gun/energy 2.5 MeV
/xe/gun/angtype flat
/xe/gun/thetarange 1.49991527091 1.64167738268 rad
/xe/gun/phirange 1.52079628527 1.62079636832 rad
#/xe/gun/phirange -2.1862 -2.5262 rad
/xe/gun/type Point
#/xe/gun/center 0 -400 0 mm


/vis/viewer/flush