/control/execute macros/no_verbose.mac
/tracking/verbose 0

/vis/scene/create
/vis/open VRML2FILE

/vis/viewer/set/viewpointThetaPhi 0 180 deg
/vis/viewer/zoom 10.0

/tracking/storeTrajectory 1
/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate

/xe/gun/particle neutron
/xe/gun/energytype Mono
/xe/gun/energy 2.5 MeV
/xe/gun/angtype flat
/xe/gun/thetarange 1.53144733265 1.61014532094 rad
/xe/gun/phirange 1.22066276901 1.29554829879 rad
/xe/gun/type Point
#/xe/gun/center 0 1700 0 mm


/vis/viewer/flush