########################################################################
#                                                                      
#              --- CAEN SpA - Computing Division ---                   
#                                                                      
#   V1190Demo Software Project                                        
#                                                                      
#   Created  :  Apr 2007      (Rel. 1.0)                                             
#                                                                      
#   Auth: NDA
#                                                                      
########################################################################

EXE	=	CAENqtpDemo

CC	=	gcc

COPTS	=	-fPIC -DLINUX -Wall 
#COPTS	=	-g -fPIC -DLINUX -Wall 

FLAGS	=	-Wall -s
#FLAGS	=	-Wall

DEPLIBS	=       -lCAENVME -lCAENqtpSDK

LIBS	=	

INCLUDEDIR =	-I. -I../include

OBJS	=	main.o user_settings.o keyb.o

INCLUDES =	../include/CAENVMELib/CAENVMElib.h ../include/CAENVMELib/CAENVMEoslib.h ../include/CAENVMELib/CAENVMEtypes.h ../include/CAENVMETool/cvt_board_commons.h ../include/CAENVMETool/cvt_common_defs.h ../include/CAENVMETool/cvt_V792.h keyb.h user_settings.h

#########################################################################

all	:	$(EXE)

clean	:
		/bin/rm -f $(OBJS) $(EXE)

$(EXE)	:	$(OBJS)
		/bin/rm -f $(EXE)
		$(CC) $(FLAGS) -o $(EXE) $(OBJS) $(DEPLIBS)

$(OBJS)	:	$(INCLUDES) makefile

%.o	:	%.c
		$(CC) $(COPTS) $(INCLUDEDIR) -c -o $@ $<

